name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cmake-args: [-DCMAKE_BUILD_TYPE=Debug -DSINTER_DEBUG_LOGLEVEL=2, -DCMAKE_BUILD_TYPE=Release]
    steps:
    - uses: actions/checkout@v2
    - name: mkdir
      run: mkdir build
    - name: cmake
      working-directory: build
      run: cmake .. ${{ matrix.cmake-args }}
    - name: make
      working-directory: build
      run: make -j4
    - name: test
      working-directory: build
      run: make CTEST_OUTPUT_ON_FAILURE=1 test
    - name: check if headers work in C++
      working-directory: vm/include
      run: g++ -std=c++11 -fsyntax-only sinter/*.h sinter.h -I. -Wall -Wextra -pedantic
